name: Publish NPM Package
on:
  pull_request:
    types:
      - closed

jobs:
  validate:
    name: PR check, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest]
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged && (startsWith(github.event.pull_request.head.ref, 'feature/') || startsWith(github.event.pull_request.head.ref, 'fix/'))

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show git repo
        run: git remote -v & git branch -al

  publish:
    needs: validate
    runs-on: ubuntu-latest
    environment:
      name: NPM_ACCESS_TOKEN

    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install deps and build (with cache)
        run: pnpm install

      # - name: Update version automatic by changeset
      #   run: pnpm changeset-version

      # - name: Build before publish
      #   run: pnpm before-publish

      # - name: Publish and tag
      #   run: pnpm changeset-publish

      # - name: Push to github
      #   run: pnpm push

      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm before-publish && pnpm changeset-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
