name: Release and tag
on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: PR check, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest]
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged && github.event.pull_request.head.ref == 'release'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show git repo
        run: git remote -v & git branch -al

  release:
    needs: validate
    runs-on: ubuntu-latest
    environment:
      name: NPM_ACCESS_TOKEN

    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Update version automatic by changeset
        id: version
        run: pnpm changeset-version

      - name: Package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Commit files
        run: |
          git config --local user.email "ulifesmile@protonmail.com"
          git config --local user.name "ulifesmile[bot]"
          git commit -a -m "chore(version): new version and tag v${{ env.PACKAGE_VERSION }}"

      - name: Create tag
        run: pnpm changeset-tag

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.PAT }}
          force_with_lease: true
