name: test
on:
  pull_request:
    types:
      - closed
jobs:
  validate:
    name: PR check, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show git repo
        run: git remote -v & git branch -al

      - name: Echo
        run: echo github.event.pull_request.base.ref=${{github.event.pull_request.base.ref}} github.event.pull_request.merged=${{github.event.pull_request.merged}} github.event.pull_request.head.ref=${{github.event.pull_request.head.ref}}
